version: "3"

services:
  db:
    image: mysql:5.5
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/RM_Test
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data: