default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: db

development:
  <<: *default
  database: RM_Test_development

test:
  <<: *default
  database: RM_Test_test

production:
  <<: *default
  database: RM_Test_production
  username: RM_Test
  password: <%= ENV['RM_TEST_DATABASE_PASSWORD'] %>
